### ISSUE TITLE
Can't connect to wallet

### ISSUE THREAD

**Issue by wimel** [Colm3na/DAppNodePackage-avalanche#28]
Using `Version: 0.1.4 (v1.3.2 upstream)` the wallet interface can't connect to the network.

![dappAvalanche](https://user-images.githubusercontent.com/17170149/116708557-1b39da00-a9d0-11eb-87a4-1768b62d0a1c.png)

Report for [node used](http://my.dappnode/#/support/report):
```
Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.44
dappmanager.dnp.dappnode.eth: 0.2.40, commit: 6838be01
https.dnp.dappnode.eth: 0.1.0
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.6
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 19.03.8
dockerCliVersion: 19.03.8
os: ubuntu
versionCodename: bionic
architecture: amd64
kernel: 4.15.0-128-generic
Disk usage: 63%
```

**Comment by tropicar** [comment]
Currently, it works, if this issue appears again, lets check it out.
It's required to stay connected to the VPN or via wifi to connect to the endpoint
